group = "promax.promax_crypto"
version = "0.2.0"

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath("com.android.tools.build:gradle:8.11.1")
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: "com.android.library"

android {
    namespace = "promax.promax_crypto"
    compileSdk = 35
    ndkVersion = android.ndkVersion

    externalNativeBuild {
        cmake {
            path = "../../../CMakeLists.txt"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        minSdk = 23
        externalNativeBuild {
            cmake {
                arguments "-DKC_BUILD_STATIC=OFF", "-DKC_BUILD_TESTS=OFF", "-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON"
            }
        }
    }
}
